services:
  mongodb:
    image: mongo:latest
    container_name: bidmania_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=AuctionDb
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  bidmania.dispatcher:
    build:
      context: .
      dockerfile: BidMania.Dispatcher/Dockerfile
    ports:
      - "5147:8080"

  bidmania.authservice:
    build:
      context: .
      dockerfile: BidMania.AuthService/Dockerfile
    ports:
      - "5148:8080"

  bidmania.auctionservice:
    build:
      context: .
      dockerfile: BidMania.AuctionService/Dockerfile
    ports:
      - "5149:8080"

  bidmania.productservice:
    build:
      context: .
      dockerfile: BidMania.ProductService/Dockerfile
    ports:
      - "5150:8080"

volumes:
  mongo_data: